name: Test on Ubuntu

on:
  push:
    branches:
      - main  # Esegui il workflow quando fai un push sul branch 'main'
  pull_request:
    branches:
      - main  # Esegui anche su pull request che vanno verso 'main'

jobs:
  test:
    runs-on: windows-latest  # Usa Ubuntu per eseguire il codice

    steps:
      # Step 1: Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup .NET SDK (imposta la versione di .NET 9)
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'  # Imposta .NET SDK versione 9.0

      # Step 3: Ripristina le dipendenze
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Costruisci il progetto
      - name: Build the project
        run: dotnet build --configuration Release

      # Step 5: Esegui i test
      - name: Run unit tests
        run: dotnet test --configuration Release
