name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0"  # Ultima versione patch di .NET 9.0

      - name: Restore dependencies
        run: dotnet restore DSx.Caching.sln

      - name: Build solution
        run: dotnet build DSx.Caching.sln --configuration Release --no-restore

      - name: Run tests with coverage
        run: |
          dotnet test \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=TestResults.trx" \
            --collect:"XPlat Code Coverage" \
            --settings tests/coverlet.runsettings \
            --results-directory TestResults

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate coverage report
        run: |
          reportgenerator \
            "-reports:TestResults/**/coverage.cobertura.xml" \
            "-targetdir:CoverageReport" \
            "-reporttypes:HtmlInline"

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: TestResults
          path: TestResults

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: CoverageReport
          path: CoverageReport