name: Build and Test .NET Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0"  # Usa .NET 9.0, puoi cambiarlo in base alle necessità

      - name: Restore dependencies
        run: dotnet restore DSx.Caching.sln

      - name: Build solution
        run: dotnet build DSx.Caching.sln --configuration Release --no-restore

      - name: Run tests with xUnit
        run: |
          dotnet test DSx.Caching.sln \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=TestResults.trx" \
            --results-directory TestResults
